"""
Constants for the Gary×Taleb Risk Dashboard Server.
Extracted to reduce magic literals and improve maintainability.
"""

# CORS Configuration
# Include Railway deployment URLs and local development
import os
RAILWAY_URL = os.environ.get("RAILWAY_PUBLIC_DOMAIN", "")
CORS_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:8000",
    f"https://{RAILWAY_URL}" if RAILWAY_URL else None,
    # Allow all origins in production if needed (configure via env)
    os.environ.get("CORS_ALLOW_ORIGIN", None),
]
# Filter out None values
CORS_ORIGINS = [origin for origin in CORS_ORIGINS if origin]

# API Endpoints
API_ROOT = "/"
API_HEALTH = "/api/health"
API_METRICS_CURRENT = "/api/metrics/current"
API_POSITIONS = "/api/positions"
API_ALERTS = "/api/alerts"
API_INEQUALITY_DATA = "/api/inequality/data"
API_CONTRARIAN_OPPORTUNITIES = "/api/contrarian/opportunities"
API_AI_STATUS = "/api/ai/status"
API_TRADE_EXECUTE = "/api/trade/execute/{asset}"
API_BARBELL_ALLOCATION = "/api/barbell/allocation"
API_AI_TIMESFM_VOLATILITY = "/api/ai/timesfm/volatility"
API_AI_TIMESFM_RISK = "/api/ai/timesfm/risk"
API_AI_FINGPT_SENTIMENT = "/api/ai/fingpt/sentiment"
API_AI_FINGPT_FORECAST = "/api/ai/fingpt/forecast"
API_AI_FEATURES_32D = "/api/ai/features/32d"
API_GATES_STATUS = "/api/gates/status"
API_TRADING_EXECUTE = "/api/trading/execute"
WS_ENDPOINT = "/ws/{client_id}"

# Symbols
SYMBOL_SPY = "SPY"
SYMBOL_QQQ = "QQQ"
SYMBOL_TLT = "TLT"
SYMBOL_GLD = "GLD"
SYMBOL_VIX = "VIX"
SYMBOL_IWM = "IWM"
SYMBOL_ULTY = "ULTY"
SYMBOL_AMDY = "AMDY"
SYMBOL_VTIP = "VTIP"
SYMBOL_IAU = "IAU"
SYMBOL_ARKK = "ARKK"
SYMBOL_TSLA = "TSLA"
SYMBOL_IEF = "IEF"
SYMBOL_SHY = "SHY"
SYMBOL_AAPL = "AAPL"
SYMBOL_MSFT = "MSFT"
SYMBOL_GOOGL = "GOOGL"
SYMBOL_AMZN = "AMZN"

RISKY_ASSETS = [SYMBOL_SPY, SYMBOL_QQQ, SYMBOL_ARKK, SYMBOL_TSLA]
SAFE_ASSETS = [SYMBOL_TLT, SYMBOL_IEF, SYMBOL_SHY]
CONTRARIAN_SYMBOLS = [SYMBOL_SPY, SYMBOL_QQQ, SYMBOL_TLT, SYMBOL_GLD, SYMBOL_VIX, SYMBOL_IWM]
KEY_SYMBOLS = [SYMBOL_SPY, SYMBOL_QQQ, SYMBOL_TLT]
MEGA_CAP_SYMBOLS = [SYMBOL_AAPL, SYMBOL_MSFT, SYMBOL_GOOGL, SYMBOL_AMZN]

# Inequality Metrics Coefficients
GINI_BASE = 0.475
GINI_FACTOR = 0.1
TOP1_BASE = 32.0
TOP1_FACTOR = 10
TOP10_BASE = 58.0
TOP10_FACTOR = 15
WAGE_GROWTH_REAL = -0.5
CORPORATE_PROFITS_TO_GDP = 12.5
HOUSEHOLD_DEBT_TO_INCOME = 105.0
LUXURY_DISCOUNT_BASE = 1.8
WEALTH_VELOCITY_BASE = 0.18
WEALTH_VELOCITY_FACTOR = 0.05
CONSENSUS_WRONG_BASE = 0.7
CONSENSUS_WRONG_FACTOR = 0.2
AI_CONFIDENCE_LEVEL = 0.75
AI_PREDICTION_BASE = 0.65
AI_PREDICTION_FACTOR = 0.1

# Historical Inequality Coefficients
HIST_GINI_BASE = 0.47
HIST_GINI_FACTOR = 0.01
HIST_TOP1_BASE = 31.0
HIST_TOP1_FACTOR = 2.0
HIST_WAGE_BASE = -0.2
HIST_WAGE_FACTOR = 2.0

# Colors
COLOR_RED = "#ef4444"
COLOR_AMBER = "#f59e0b"
COLOR_VIOLET = "#8b5cf6"
COLOR_EMERALD = "#10b981"

# Wealth Flow Values
FLOW_WAGES_VALUE = 25.0
FLOW_SAVINGS_VALUE_DEFAULT = 35.0
FLOW_DEBT_VALUE = 18.0
FLOW_RENT_VALUE = 22.0

# Risk Thresholds
RISK_P_RUIN_THRESHOLD = 0.10
RISK_P_RUIN_HIGH = 0.15
RISK_DRAWDOWN_THRESHOLD = 0.20
RISK_DRAWDOWN_CRITICAL = 0.30
RISK_VOLATILITY_THRESHOLD = 0.30

# Defaults
DEFAULT_PORTFOLIO_VALUE = 10000
DEFAULT_CASH_RATIO = 0.3
DEFAULT_MARGIN_RATIO = 0.7
DEFAULT_VOLATILITY = 0.2
DEFAULT_RSI = 50
DEFAULT_MODEL_PARAMS = 156502027
