"""
Strategy Selector Model

Neural network that maps 38D market features to optimal strategy selection.

Input: EnhancedFeatureVector (38D)
Output: Strategy ID (0-7) + confidence scores

The selector learns WHEN to use each of the 8 black swan strategies
based on market conditions captured in the feature vector.
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Union
from dataclasses import dataclass
import logging
import pickle
from pathlib import Path

logger = logging.getLogger(__name__)

# Try to import sklearn
try:
    from sklearn.neural_network import MLPClassifier
    from sklearn.preprocessing import StandardScaler
    from sklearn.model_selection import TimeSeriesSplit
    from sklearn.metrics import (
        accuracy_score,
        precision_score,
        recall_score,
        f1_score,
        confusion_matrix,
    )
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False
    logger.warning("scikit-learn not available - using fallback selector")


@dataclass
class SelectionResult:
    """Result of strategy selection."""
    strategy_id: int
    strategy_name: str
    confidence: float
    all_probabilities: Dict[int, float]
    features_used: int


@dataclass
class SelectorMetrics:
    """Training/evaluation metrics for the selector."""
    accuracy: float
    precision_per_class: Dict[int, float]
    recall_per_class: Dict[int, float]
    f1_per_class: Dict[int, float]
    confusion_matrix: np.ndarray
    n_samples: int
    n_classes: int


# Strategy names for reference
STRATEGY_NAMES = [
    "tail_hedge",           # 0
    "volatility_harvest",   # 1
    "crisis_alpha",         # 2
    "momentum_explosion",   # 3
    "mean_reversion",       # 4
    "correlation_breakdown", # 5
    "inequality_arbitrage", # 6
    "event_catalyst",       # 7
]


class StrategySelector:
    """
    Neural network selector for choosing optimal strategy from 8 candidates.

    Architecture:
    - Input: 38D feature vector (24 base + 8 AI + 6 signal features)
    - Hidden: 2-3 layers with ReLU activation
    - Output: 8-class softmax (one per strategy)

    Training:
    - Uses walk-forward cross-validation
    - Labels generated by forward-looking returns (see strategy_labeler.py)
    - Optimized for selection accuracy AND downstream profit factor
    """

    def __init__(
        self,
        input_dim: int = 38,
        hidden_layers: Tuple[int, ...] = (64, 32),
        learning_rate: float = 0.001,
        max_iter: int = 500,
        random_state: int = 42,
    ):
        """
        Initialize strategy selector.

        Args:
            input_dim: Input feature dimension (default: 38)
            hidden_layers: Tuple of hidden layer sizes
            learning_rate: Learning rate for optimizer
            max_iter: Maximum training iterations
            random_state: Random seed for reproducibility
        """
        self.input_dim = input_dim
        self.hidden_layers = hidden_layers
        self.learning_rate = learning_rate
        self.max_iter = max_iter
        self.random_state = random_state

        self.n_strategies = 8
        self.strategy_names = STRATEGY_NAMES

        self.model = None
        self.scaler = None
        self.is_trained = False
        self.training_metrics = None

        if SKLEARN_AVAILABLE:
            self._initialize_model()
        else:
            logger.warning("Using fallback rule-based selector")

    def _initialize_model(self):
        """Initialize the MLP classifier."""
        self.model = MLPClassifier(
            hidden_layer_sizes=self.hidden_layers,
            activation='relu',
            solver='adam',
            learning_rate_init=self.learning_rate,
            max_iter=self.max_iter,
            random_state=self.random_state,
            early_stopping=True,
            validation_fraction=0.1,
            n_iter_no_change=20,
        )
        self.scaler = StandardScaler()

    def fit(
        self,
        X: np.ndarray,
        y: np.ndarray,
        sample_weights: Optional[np.ndarray] = None,
    ) -> SelectorMetrics:
        """
        Train the selector on labeled data.

        Args:
            X: Feature matrix of shape (n_samples, 38)
            y: Strategy labels of shape (n_samples,) with values 0-7
            sample_weights: Optional weights for each sample

        Returns:
            Training metrics
        """
        if not SKLEARN_AVAILABLE:
            logger.warning("sklearn not available, using fallback")
            self.is_trained = True
            return self._fallback_metrics()

        logger.info(f"Training selector on {len(X)} samples")

        # Scale features
        X_scaled = self.scaler.fit_transform(X)

        # Train model
        self.model.fit(X_scaled, y)
        self.is_trained = True

        # Compute metrics
        y_pred = self.model.predict(X_scaled)
        self.training_metrics = self._compute_metrics(y, y_pred)

        logger.info(f"Training accuracy: {self.training_metrics.accuracy:.3f}")

        return self.training_metrics

    def predict(self, X: np.ndarray) -> np.ndarray:
        """
        Predict strategy IDs for feature vectors.

        Args:
            X: Feature matrix of shape (n_samples, 38)

        Returns:
            Predicted strategy IDs of shape (n_samples,)
        """
        if not self.is_trained:
            raise RuntimeError("Selector not trained. Call fit() first.")

        if not SKLEARN_AVAILABLE:
            return self._fallback_predict(X)

        X_scaled = self.scaler.transform(X)
        return self.model.predict(X_scaled)

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """
        Get probability distribution over strategies.

        Args:
            X: Feature matrix of shape (n_samples, 38)

        Returns:
            Probabilities of shape (n_samples, 8)
        """
        if not self.is_trained:
            raise RuntimeError("Selector not trained. Call fit() first.")

        if not SKLEARN_AVAILABLE:
            return self._fallback_predict_proba(X)

        X_scaled = self.scaler.transform(X)
        return self.model.predict_proba(X_scaled)

    def select_strategy(self, features: np.ndarray) -> SelectionResult:
        """
        Select optimal strategy for given market features.

        Args:
            features: Feature vector of shape (38,) or (1, 38)

        Returns:
            SelectionResult with strategy ID, name, and confidence
        """
        if features.ndim == 1:
            features = features.reshape(1, -1)

        probs = self.predict_proba(features)[0]
        strategy_id = int(np.argmax(probs))
        confidence = float(probs[strategy_id])

        all_probs = {i: float(p) for i, p in enumerate(probs)}

        return SelectionResult(
            strategy_id=strategy_id,
            strategy_name=self.strategy_names[strategy_id],
            confidence=confidence,
            all_probabilities=all_probs,
            features_used=features.shape[1],
        )

    def evaluate(self, X: np.ndarray, y: np.ndarray) -> SelectorMetrics:
        """
        Evaluate selector on test data.

        Args:
            X: Feature matrix
            y: True labels

        Returns:
            Evaluation metrics
        """
        y_pred = self.predict(X)
        return self._compute_metrics(y, y_pred)

    def _compute_metrics(self, y_true: np.ndarray, y_pred: np.ndarray) -> SelectorMetrics:
        """Compute classification metrics."""
        # Get unique classes present
        classes = sorted(set(y_true) | set(y_pred))

        # Accuracy
        accuracy = accuracy_score(y_true, y_pred)

        # Per-class metrics
        precision = precision_score(y_true, y_pred, average=None, zero_division=0)
        recall = recall_score(y_true, y_pred, average=None, zero_division=0)
        f1 = f1_score(y_true, y_pred, average=None, zero_division=0)

        # Build dicts with all 8 classes
        precision_dict = {i: 0.0 for i in range(8)}
        recall_dict = {i: 0.0 for i in range(8)}
        f1_dict = {i: 0.0 for i in range(8)}

        for idx, cls in enumerate(classes):
            if idx < len(precision):
                precision_dict[cls] = float(precision[idx])
                recall_dict[cls] = float(recall[idx])
                f1_dict[cls] = float(f1[idx])

        # Confusion matrix
        cm = confusion_matrix(y_true, y_pred, labels=list(range(8)))

        return SelectorMetrics(
            accuracy=accuracy,
            precision_per_class=precision_dict,
            recall_per_class=recall_dict,
            f1_per_class=f1_dict,
            confusion_matrix=cm,
            n_samples=len(y_true),
            n_classes=len(classes),
        )

    def _fallback_predict(self, X: np.ndarray) -> np.ndarray:
        """Rule-based fallback when sklearn unavailable."""
        # Simple heuristic based on volatility and trend
        predictions = []

        for features in X:
            if len(features) < 10:
                predictions.append(4)  # Default to mean reversion
                continue

            # Use first few features as proxies
            volatility = abs(features[0]) if len(features) > 0 else 0.5
            trend = features[1] if len(features) > 1 else 0

            if volatility > 0.3:
                if trend < -0.02:
                    predictions.append(2)  # Crisis alpha
                else:
                    predictions.append(1)  # Volatility harvest
            elif volatility < 0.15:
                predictions.append(0)  # Tail hedge
            elif trend > 0.02:
                predictions.append(3)  # Momentum
            elif trend < -0.02:
                predictions.append(4)  # Mean reversion
            else:
                predictions.append(5)  # Correlation breakdown

        return np.array(predictions)

    def _fallback_predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Rule-based probability fallback."""
        predictions = self._fallback_predict(X)
        probs = np.zeros((len(X), 8))

        for i, pred in enumerate(predictions):
            probs[i, pred] = 0.7
            # Distribute remaining probability
            for j in range(8):
                if j != pred:
                    probs[i, j] = 0.3 / 7

        return probs

    def _fallback_metrics(self) -> SelectorMetrics:
        """Return dummy metrics for fallback mode."""
        return SelectorMetrics(
            accuracy=0.0,
            precision_per_class={i: 0.0 for i in range(8)},
            recall_per_class={i: 0.0 for i in range(8)},
            f1_per_class={i: 0.0 for i in range(8)},
            confusion_matrix=np.zeros((8, 8)),
            n_samples=0,
            n_classes=8,
        )

    def save(self, path: Union[str, Path]):
        """Save selector to file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        state = {
            'input_dim': self.input_dim,
            'hidden_layers': self.hidden_layers,
            'learning_rate': self.learning_rate,
            'max_iter': self.max_iter,
            'random_state': self.random_state,
            'is_trained': self.is_trained,
            'model': self.model,
            'scaler': self.scaler,
            'training_metrics': self.training_metrics,
        }

        with open(path, 'wb') as f:
            pickle.dump(state, f)

        logger.info(f"Selector saved to {path}")

    @classmethod
    def load(cls, path: Union[str, Path]) -> 'StrategySelector':
        """Load selector from file."""
        with open(path, 'rb') as f:
            state = pickle.load(f)

        selector = cls(
            input_dim=state['input_dim'],
            hidden_layers=state['hidden_layers'],
            learning_rate=state['learning_rate'],
            max_iter=state['max_iter'],
            random_state=state['random_state'],
        )

        selector.model = state['model']
        selector.scaler = state['scaler']
        selector.is_trained = state['is_trained']
        selector.training_metrics = state['training_metrics']

        logger.info(f"Selector loaded from {path}")
        return selector

    def get_feature_importance(self) -> Optional[Dict[int, float]]:
        """
        Get feature importance scores (if available).

        For MLP, this is approximate based on weight magnitudes.
        """
        if not self.is_trained or self.model is None:
            return None

        if not hasattr(self.model, 'coefs_'):
            return None

        # Use first layer weights as proxy for importance
        weights = np.abs(self.model.coefs_[0])
        importance = weights.sum(axis=1)
        importance = importance / importance.sum()

        return {i: float(importance[i]) for i in range(len(importance))}


def create_ensemble_selector(
    selectors: List[StrategySelector],
    weights: Optional[List[float]] = None,
) -> 'EnsembleSelector':
    """Create an ensemble of multiple selectors."""
    return EnsembleSelector(selectors, weights)


class EnsembleSelector:
    """Ensemble of multiple strategy selectors."""

    def __init__(
        self,
        selectors: List[StrategySelector],
        weights: Optional[List[float]] = None,
    ):
        self.selectors = selectors
        self.weights = weights or [1.0 / len(selectors)] * len(selectors)
        self.strategy_names = STRATEGY_NAMES

    def predict_proba(self, X: np.ndarray) -> np.ndarray:
        """Weighted average of selector predictions."""
        probs = np.zeros((len(X), 8))

        for selector, weight in zip(self.selectors, self.weights):
            probs += weight * selector.predict_proba(X)

        return probs

    def select_strategy(self, features: np.ndarray) -> SelectionResult:
        """Select using ensemble voting."""
        if features.ndim == 1:
            features = features.reshape(1, -1)

        probs = self.predict_proba(features)[0]
        strategy_id = int(np.argmax(probs))

        return SelectionResult(
            strategy_id=strategy_id,
            strategy_name=self.strategy_names[strategy_id],
            confidence=float(probs[strategy_id]),
            all_probabilities={i: float(p) for i, p in enumerate(probs)},
            features_used=features.shape[1],
        )


if __name__ == "__main__":
    # Test strategy selector
    print("=== Strategy Selector Test ===")

    np.random.seed(42)

    # Generate synthetic training data
    n_samples = 500
    n_features = 38

    X = np.random.randn(n_samples, n_features)
    y = np.random.randint(0, 8, n_samples)

    # Split into train/test
    train_size = int(0.8 * n_samples)
    X_train, X_test = X[:train_size], X[train_size:]
    y_train, y_test = y[:train_size], y[train_size:]

    # Create and train selector
    selector = StrategySelector(input_dim=38, hidden_layers=(64, 32))

    print(f"\nTraining on {len(X_train)} samples...")
    train_metrics = selector.fit(X_train, y_train)
    print(f"Training accuracy: {train_metrics.accuracy:.3f}")

    # Evaluate
    print(f"\nEvaluating on {len(X_test)} samples...")
    test_metrics = selector.evaluate(X_test, y_test)
    print(f"Test accuracy: {test_metrics.accuracy:.3f}")

    # Test selection
    print("\nTesting single selection...")
    result = selector.select_strategy(X_test[0])
    print(f"Selected: {result.strategy_name} (ID: {result.strategy_id})")
    print(f"Confidence: {result.confidence:.3f}")
    print(f"Top 3 probabilities:")
    sorted_probs = sorted(result.all_probabilities.items(), key=lambda x: -x[1])
    for sid, prob in sorted_probs[:3]:
        print(f"  {STRATEGY_NAMES[sid]}: {prob:.3f}")

    # Test save/load
    print("\nTesting save/load...")
    selector.save("outputs/test_selector.pkl")
    loaded = StrategySelector.load("outputs/test_selector.pkl")
    loaded_result = loaded.select_strategy(X_test[0])
    print(f"Loaded selector result: {loaded_result.strategy_name}")

    print("\n=== Test Complete ===")
