"""
Strategy Selector Training Pipeline

Trains the StrategySelector using walk-forward cross-validation.
Generates training labels based on which strategy would have performed
best at each historical point.

MLflow integration for experiment tracking.
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Callable
from dataclasses import dataclass, field
from pathlib import Path
from datetime import datetime
import logging
import json

# Try MLflow import
try:
    import mlflow
    MLFLOW_AVAILABLE = True
except ImportError:
    MLFLOW_AVAILABLE = False

logger = logging.getLogger(__name__)


@dataclass
class TrainingConfig:
    """Configuration for selector training."""
    # Data
    train_window: int = 252 * 4  # 4 years
    test_window: int = 63       # 3 months
    min_samples_per_class: int = 10

    # Model
    hidden_layers: Tuple[int, ...] = (64, 32)
    learning_rate: float = 0.001
    max_iter: int = 500

    # Walk-forward
    n_splits: int = 5
    expanding_window: bool = True

    # Labels
    forward_horizon: int = 20  # Days to look ahead for labeling
    label_metric: str = 'sharpe'  # 'return', 'sharpe', 'profit_factor'

    # MLflow
    experiment_name: str = 'trader-ai-strategy-selector'
    run_name_prefix: str = 'selector'


@dataclass
class TrainingResult:
    """Result of selector training."""
    train_accuracy: float
    test_accuracy: float
    per_fold_accuracy: List[float]
    per_class_precision: Dict[int, float]
    per_class_recall: Dict[int, float]
    confusion_matrix: np.ndarray
    n_train_samples: int
    n_test_samples: int
    best_fold: int
    training_time_seconds: float
    model_path: Optional[str] = None
    mlflow_run_id: Optional[str] = None


class StrategySelectorTrainer:
    """
    Training pipeline for the strategy selector.

    Uses walk-forward cross-validation to ensure no lookahead bias.
    Labels are generated by computing which strategy would have performed
    best over the forward horizon at each point in time.
    """

    def __init__(self, config: Optional[TrainingConfig] = None):
        """
        Initialize trainer.

        Args:
            config: Training configuration
        """
        self.config = config or TrainingConfig()
        self.label_generator = None

    def prepare_training_data(
        self,
        features_df: pd.DataFrame,
        ohlcv_df: pd.DataFrame,
        strategy_signals: Dict[int, Callable],
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Prepare training data by generating labels.

        Args:
            features_df: DataFrame with 38D features per bar
            ohlcv_df: OHLCV DataFrame for strategy simulation
            strategy_signals: Dict mapping strategy_id -> signal_function

        Returns:
            X: Feature matrix (n_samples, 38)
            y: Strategy labels (n_samples,)
        """
        logger.info("Preparing training data...")

        n_samples = len(features_df)
        horizon = self.config.forward_horizon

        # Generate labels
        labels = np.zeros(n_samples, dtype=int)

        for idx in range(n_samples - horizon):
            # Get forward window
            forward_window = ohlcv_df.iloc[idx:idx + horizon + 1]

            if len(forward_window) < horizon:
                continue

            # Compute performance for each strategy
            best_score = -np.inf
            best_strategy = 0

            for strategy_id, signal_fn in strategy_signals.items():
                try:
                    score = self._evaluate_strategy_forward(
                        signal_fn, forward_window, self.config.label_metric
                    )
                    if score > best_score:
                        best_score = score
                        best_strategy = strategy_id
                except Exception as e:
                    logger.debug(f"Strategy {strategy_id} failed at idx {idx}: {e}")

            labels[idx] = best_strategy

        # Extract features
        if isinstance(features_df, pd.DataFrame):
            X = features_df.values[:n_samples - horizon]
        else:
            X = features_df[:n_samples - horizon]

        y = labels[:n_samples - horizon]

        logger.info(f"Prepared {len(X)} samples with {len(np.unique(y))} classes")

        return X, y

    def _evaluate_strategy_forward(
        self,
        signal_fn: Callable,
        ohlcv_window: pd.DataFrame,
        metric: str = 'sharpe',
    ) -> float:
        """Evaluate strategy over forward window."""
        from ..strategy_lab.signal_interface import (
            position_from_signal_function,
            strategy_returns,
        )
        from ..validation.objectives import (
            sharpe_ratio,
            profit_factor,
        )

        # Get positions
        positions = position_from_signal_function(ohlcv_window, signal_fn)

        # Calculate returns
        returns = strategy_returns(ohlcv_window['close'].values, positions)

        if len(returns) == 0 or np.all(returns == 0):
            return 0.0

        # Compute metric
        if metric == 'return':
            return np.sum(returns)
        elif metric == 'sharpe':
            return sharpe_ratio(returns)
        elif metric == 'profit_factor':
            return profit_factor(returns)
        else:
            return np.sum(returns)

    def train_walk_forward(
        self,
        X: np.ndarray,
        y: np.ndarray,
        save_path: Optional[str] = None,
    ) -> TrainingResult:
        """
        Train selector using walk-forward cross-validation.

        Args:
            X: Feature matrix (n_samples, 38)
            y: Strategy labels (n_samples,)
            save_path: Path to save best model

        Returns:
            TrainingResult with metrics and model path
        """
        from ..strategy_lab.strategy_selector import StrategySelector
        from sklearn.model_selection import TimeSeriesSplit

        logger.info(f"Starting walk-forward training with {self.config.n_splits} splits")
        start_time = datetime.now()

        # Initialize MLflow
        mlflow_run_id = None
        if MLFLOW_AVAILABLE:
            mlflow.set_experiment(self.config.experiment_name)
            run_name = f"{self.config.run_name_prefix}__{datetime.now().strftime('%Y%m%d_%H%M%S')}"
            mlflow.start_run(run_name=run_name)
            mlflow_run_id = mlflow.active_run().info.run_id

            # Log config
            mlflow.log_params({
                'train_window': self.config.train_window,
                'test_window': self.config.test_window,
                'n_splits': self.config.n_splits,
                'hidden_layers': str(self.config.hidden_layers),
                'learning_rate': self.config.learning_rate,
                'forward_horizon': self.config.forward_horizon,
                'label_metric': self.config.label_metric,
            })

        # Time series split
        tscv = TimeSeriesSplit(n_splits=self.config.n_splits)

        fold_results = []
        best_accuracy = 0.0
        best_model = None
        best_fold = 0

        for fold, (train_idx, test_idx) in enumerate(tscv.split(X)):
            logger.info(f"\nFold {fold + 1}/{self.config.n_splits}")

            X_train, X_test = X[train_idx], X[test_idx]
            y_train, y_test = y[train_idx], y[test_idx]

            logger.info(f"  Train: {len(X_train)} samples")
            logger.info(f"  Test: {len(X_test)} samples")

            # Create and train selector
            selector = StrategySelector(
                input_dim=X.shape[1],
                hidden_layers=self.config.hidden_layers,
                learning_rate=self.config.learning_rate,
                max_iter=self.config.max_iter,
            )

            train_metrics = selector.fit(X_train, y_train)
            test_metrics = selector.evaluate(X_test, y_test)

            fold_results.append({
                'fold': fold,
                'train_accuracy': train_metrics.accuracy,
                'test_accuracy': test_metrics.accuracy,
                'n_train': len(X_train),
                'n_test': len(X_test),
            })

            logger.info(f"  Train accuracy: {train_metrics.accuracy:.3f}")
            logger.info(f"  Test accuracy: {test_metrics.accuracy:.3f}")

            if MLFLOW_AVAILABLE:
                mlflow.log_metrics({
                    f'fold_{fold}_train_accuracy': train_metrics.accuracy,
                    f'fold_{fold}_test_accuracy': test_metrics.accuracy,
                }, step=fold)

            # Track best model
            if test_metrics.accuracy > best_accuracy:
                best_accuracy = test_metrics.accuracy
                best_model = selector
                best_fold = fold

        # Final training on all data with best config
        logger.info("\nTraining final model on all data...")
        final_selector = StrategySelector(
            input_dim=X.shape[1],
            hidden_layers=self.config.hidden_layers,
            learning_rate=self.config.learning_rate,
            max_iter=self.config.max_iter,
        )
        final_metrics = final_selector.fit(X, y)

        # Save model
        model_path = None
        if save_path:
            model_path = save_path
            final_selector.save(model_path)
            logger.info(f"Model saved to {model_path}")

            if MLFLOW_AVAILABLE:
                mlflow.log_artifact(model_path)

        # Compute aggregate metrics
        training_time = (datetime.now() - start_time).total_seconds()

        result = TrainingResult(
            train_accuracy=final_metrics.accuracy,
            test_accuracy=np.mean([r['test_accuracy'] for r in fold_results]),
            per_fold_accuracy=[r['test_accuracy'] for r in fold_results],
            per_class_precision=final_metrics.precision_per_class,
            per_class_recall=final_metrics.recall_per_class,
            confusion_matrix=final_metrics.confusion_matrix,
            n_train_samples=len(X),
            n_test_samples=sum(r['n_test'] for r in fold_results),
            best_fold=best_fold,
            training_time_seconds=training_time,
            model_path=model_path,
            mlflow_run_id=mlflow_run_id,
        )

        if MLFLOW_AVAILABLE:
            mlflow.log_metrics({
                'final_train_accuracy': result.train_accuracy,
                'mean_test_accuracy': result.test_accuracy,
                'best_fold_accuracy': best_accuracy,
                'training_time_seconds': training_time,
            })
            mlflow.end_run()

        logger.info(f"\nTraining complete in {training_time:.1f}s")
        logger.info(f"Final train accuracy: {result.train_accuracy:.3f}")
        logger.info(f"Mean test accuracy: {result.test_accuracy:.3f}")

        return result

    def train_with_labeler(
        self,
        ohlcv_df: pd.DataFrame,
        feature_generator: Callable,
        strategy_signals: Dict[int, Callable],
        save_path: Optional[str] = None,
    ) -> TrainingResult:
        """
        Full training pipeline with feature and label generation.

        Args:
            ohlcv_df: OHLCV DataFrame
            feature_generator: Function to generate 38D features from OHLCV
            strategy_signals: Dict mapping strategy_id -> signal_function
            save_path: Path to save model

        Returns:
            TrainingResult
        """
        logger.info("Running full training pipeline...")

        # Generate features
        logger.info("Generating features...")
        features = []
        for idx in range(len(ohlcv_df)):
            try:
                feat = feature_generator(ohlcv_df.iloc[:idx + 1])
                features.append(feat)
            except Exception as e:
                # Use zeros for failed feature generation
                features.append(np.zeros(38))

        features_df = pd.DataFrame(features)

        # Prepare training data
        X, y = self.prepare_training_data(features_df, ohlcv_df, strategy_signals)

        # Train
        return self.train_walk_forward(X, y, save_path)


def create_default_signal_functions() -> Dict[int, Callable]:
    """
    Create default signal functions for the 8 strategies.

    These are simplified versions for training label generation.
    """
    def tail_hedge_signal(df, idx):
        if idx < 20:
            return 0
        returns = np.diff(np.log(df['close'].iloc[:idx+1].values[-20:]))
        vol = np.std(returns) * np.sqrt(252) * 100
        return 1 if vol < 15 else 0

    def volatility_harvest_signal(df, idx):
        if idx < 30:
            return 0
        returns = np.diff(np.log(df['close'].iloc[:idx+1].values[-20:]))
        vol = np.std(returns) * np.sqrt(252) * 100
        return 1 if vol > 25 else 0

    def crisis_alpha_signal(df, idx):
        if idx < 20:
            return 0
        close = df['close'].iloc[:idx+1].values
        max_close = np.max(close)
        drawdown = (close[-1] - max_close) / max_close
        return 1 if drawdown < -0.05 else 0

    def momentum_signal(df, idx):
        if idx < 20:
            return 0
        returns_20d = df['close'].iloc[idx] / df['close'].iloc[idx-20] - 1
        if returns_20d > 0.03:
            return 1
        elif returns_20d < -0.03:
            return -1
        return 0

    def mean_reversion_signal(df, idx):
        if idx < 50:
            return 0
        close = df['close'].iloc[:idx+1].values
        ma_50 = np.mean(close[-50:])
        deviation = (close[-1] - ma_50) / ma_50
        if deviation < -0.05:
            return 1
        elif deviation > 0.05:
            return -1
        return 0

    def correlation_breakdown_signal(df, idx):
        if idx < 30:
            return 0
        returns_5d = df['close'].iloc[idx] / df['close'].iloc[idx-5] - 1
        returns_20d = df['close'].iloc[idx] / df['close'].iloc[idx-20] - 1
        if abs(returns_5d - returns_20d) > 0.02:
            return 1 if returns_5d > 0 else -1
        return 0

    def inequality_arb_signal(df, idx):
        if idx < 10:
            return 0
        returns_5d = df['close'].iloc[idx] / df['close'].iloc[idx-5] - 1
        if returns_5d < -0.03:
            return 1
        elif returns_5d > 0.03:
            return -1
        return 0

    def event_catalyst_signal(df, idx):
        if idx < 10:
            return 0
        if 'volume' not in df.columns:
            return 0
        vol_ratio = df['volume'].iloc[idx] / df['volume'].iloc[idx-10:idx].mean()
        if vol_ratio > 1.5:
            returns_1d = df['close'].iloc[idx] / df['close'].iloc[idx-1] - 1
            return 1 if returns_1d > 0 else -1
        return 0

    return {
        0: tail_hedge_signal,
        1: volatility_harvest_signal,
        2: crisis_alpha_signal,
        3: momentum_signal,
        4: mean_reversion_signal,
        5: correlation_breakdown_signal,
        6: inequality_arb_signal,
        7: event_catalyst_signal,
    }


if __name__ == "__main__":
    # Test training pipeline
    print("=== Selector Training Test ===")

    np.random.seed(42)

    # Generate synthetic data
    n_bars = 500
    close = 100 * np.exp(np.cumsum(np.random.randn(n_bars) * 0.01))
    high = close * (1 + np.abs(np.random.randn(n_bars) * 0.005))
    low = close * (1 - np.abs(np.random.randn(n_bars) * 0.005))
    open_price = np.roll(close, 1) + np.random.randn(n_bars) * 0.1
    volume = np.random.uniform(1e6, 5e6, n_bars)

    ohlcv_df = pd.DataFrame({
        'open': open_price,
        'high': high,
        'low': low,
        'close': close,
        'volume': volume,
    })

    # Generate synthetic features
    X = np.random.randn(n_bars, 38)
    y = np.random.randint(0, 8, n_bars)

    # Create trainer
    config = TrainingConfig(
        n_splits=3,
        max_iter=100,
    )
    trainer = StrategySelectorTrainer(config)

    # Train
    print("\nTraining selector...")
    result = trainer.train_walk_forward(X, y)

    print(f"\nResults:")
    print(f"  Train accuracy: {result.train_accuracy:.3f}")
    print(f"  Test accuracy: {result.test_accuracy:.3f}")
    print(f"  Best fold: {result.best_fold}")
    print(f"  Training time: {result.training_time_seconds:.1f}s")

    print("\n=== Test Complete ===")
